# This is a basic workflow that is nightly triggered

name: Python 3.14 nightly tests

# Controls when the action will run. CRON schedule runs at mm hh dd mm yy UTC TIME
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run_tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.14"

    - name: Checkout acherus
      uses: actions/checkout@v4
      with:
        path: acherus

    - name: pip install
      run:  |
        cd acherus
        python -m pip install --upgrade pip
        pip install .
        pip install pytest pytest-cov

    - name: Print versions
      run: |
        python --version
        python -m pip freeze

    - name: Run pytest
      run:  |
        cd acherus
        python -m pytest --cov=acherus --cov-config=tests/.coveragerc --cov-report=term -v tests
